#pragma once
#include "Mario.h"
#include <iostream>
#include <algorithm>
#include <vector>
#include "collider.h"
#include "collisions.h"
#include "Block.h"
#include "item.h"
#include "goomba.h"
#include "koopa.h"
#include "Spinning_coin.h"
#include "Brick_part.h"
#include "FireBall.h"
#include "Warp.h"
#include <fstream>
#include <string> 
#include <tileson.hpp>
#include "flag.h"
#include "sort.h"
#include "score.h"
#include <C:\jsoncpp-master\jsoncpp-master\dist\json\json.h>
#include "plant.h"